# Add seed data here. Seed your database with `rake db:seed`
User.create(name: "Ariel")
User.create(name: "Vijay")
User.create(name: "Kyle")
User.create(name: "Gene")

Photo.create(title: "Cool Cat", url: "https://i.imgur.com/3R3iYvP.jpg", user_id: 1)
Photo.create(title: "Ice Cream", url: "http://www.bravotv.com/sites/nbcubravotv/files/field_blog_image/2016/12/the-feast-ice-cream-museum-promote.jpg", user_id: 2)
Photo.create(title: "Underwater", url: "https://www.telesurtv.net/__export/1465827445977/sites/telesur/img/news/2016/06/13/costa_rica_reefs.jpg_1718483346.jpg", user_id: 4)
Photo.create(title: "Solange", url: "https://media.wmagazine.com/photos/5820ab976c6e10fd162f70f7/4:3/w_1536/GettyImages-621447922.jpg", user_id: 3)
Photo.create(title: "Flatiron School", url: "http://blog.flatironschool.com/wp-content/uploads/2014/07/tumblr_n94ygratuU1rlyp8co6_12801.jpg", user_id: 3)
Photo.create(title: "Salsa Dance", url: "http://dancefreak.com/wp-content/uploads/2015/11/salsa-bootcamps.jpg", user_id: 4)
Photo.create(title: "I Know What You Did Last Summer", url:"http://assets.nydailynews.com/polopoly_fs/1.1941842.1410899023!/img/httpImage/image.jpg_gen/derivatives/article_750/aqu112-034.jpg", user_id: 1)
Photo.create(title: "Nebulise Me!", url: "http://coolcosmos.ipac.caltech.edu/system/avm_image_sqls/binaries/177/larger/eso_eso1205a_3000.jpg?1374616594", user_id: 1)
Photo.create(title: "Mountain Goat", url: "https://s.w-x.co/gettyimages-518980030_0.jpg", user_id:2)
Photo.create(title: "Too Weird for Tags", url: "https://cdn-jpg3.thedailymeal.com/sites/default/files/styles/tdm_slideshow_large/public/2017/05/09/1_Big%20Banana%20Car_mutant%20brothers_edit_0.jpg?itok=-BIMMgwK", user_id: 1)


Tag.create(name: "cool")
Tag.create(name: "amazing")
Tag.create(name: "space")
Tag.create(name: "food")
Tag.create(name: "animals")
Tag.create(name: "party")
Tag.create(name: "education")
Tag.create(name: "movies")

PhotoTag.create(photo_id: 1, tag_id: 1)
PhotoTag.create(photo_id: 1, tag_id: 5)
PhotoTag.create(photo_id: 2, tag_id: 4)
PhotoTag.create(photo_id: 3, tag_id: 5)
PhotoTag.create(photo_id: 4, tag_id: 2)
PhotoTag.create(photo_id: 5, tag_id: 7)
PhotoTag.create(photo_id: 6, tag_id: 6)
PhotoTag.create(photo_id: 7, tag_id: 9)
PhotoTag.create(photo_id: 8, tag_id: 3)
PhotoTag.create(photo_id: 9, tag_id: 5)
PhotoTag.create(photo_id: 9, tag_id: 7)
